server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
#媒体配置
media:
  upload-location: F:/video/
  chunkSize: 5242880 # 1024 * 1024 * 5    分块文件为5M